server:
  port: 9000
spring:
  application:
       name: LOGIN-SERVICE
  config:
      import: configserver:http://localhost:8888
  zipkin:
     base-url:  http://localhost:9411            
eureka:
   client:
      register-with-eureka: true
      fetch-registry: true
   instance:
      prefer-ip-address: true
      
     