server:
  port: 9001
spring:
  application:
       name: MASTERDATA-SERVICE
  config:
      import: configserver:http://localhost:8888
#  datasource:
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/olx-masterdata
#        username: root
#        password: Saketh1@
#
#  jpa:
#        generate-ddl: true
#        show-sql: true
#        
#        hibernate:
#            ddl-auto: update
#            dialect: org.hibernate.dialect.MySQL8Dialect
  zipkin:
     base-url:  http://localhost:9411            
            
eureka:
   client:
      register-with-eureka: true
      fetch-registry: true
   instance:
      prefer-ip-address: true


