server:
  port: 9002
  
spring:
 
# datasource:
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/olx-test-advertises
#        username: root
#        password: Saketh1@
# jpa:
#        hibernate:
#          ddl-auto: update
#        properties:
#          hibernate:
#            dialect: org.hibernate.dialect.MySQL8Dialect
            
 application:
       name: ADVERTISE-SERVICE
 config:
     import: configserver:http://localhost:8888
 
 zipkin:
     base-url:  http://localhost:9411


eureka:
  client:
      register-with-eureka: true
      fetch-registry: true 
  instance:
      prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always
      
resilience4j:
  circuitbreaker:
    instances:
      CATEGORY-CIRCUIT-BREAKER:
        registerHealthIndicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s 
      ADVERTISE-CIRCUIT-BREAKER:
        registerHealthIndicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s       




     

           
         
            

 
  