
spring:
  application:
    name: configuration-server
  cloud:
    config:
      server:
        git:
          #uri: https://github.com/your-github-username/olx-config
          uri:  https://github.com/udayappdeveloper/olx-config
          username: udayappdeveloper@gmail.com
          password: Saketh1@
          clone-on-start: true
          
server:
  port: 8888